"""Data models for MCDA scoring, optimization results, and explainability outputs."""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field
from .civic_issue import CivicIssue, PriorityLevel, IssueValidationReport
from .resources import MunicipalResources, ResourceUsage
from .authority import AuthorityRoutingResult


class MCDAFactorScores(BaseModel):
    """Normalized scores (0-100), weights, and weighted points per MCDA factor."""
    normalized_severity: float = Field(..., ge=0.0, le=100.0, description="Normalized severity (0-100)")
    normalized_urgency: float = Field(..., ge=0.0, le=100.0, description="Normalized urgency (0-100)")
    normalized_population_affected: float = Field(..., ge=0.0, le=100.0, description="Normalized population affected (0-100)")
    normalized_health_safety_impact: float = Field(..., ge=0.0, le=100.0, description="Normalized health/safety risk (0-100)")
    normalized_location_sensitivity: float = Field(..., ge=0.0, le=100.0, description="Normalized location sensitivity (0-100)")
    normalized_complaint_age: float = Field(..., ge=0.0, le=100.0, description="Normalized complaint age (0-100)")
    
    factor_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Assigned MCDA weight for each factor"
    )
    weighted_contributions: Dict[str, float] = Field(
        default_factory=dict,
        description="Weighted points contributed by each criterion toward the composite score"
    )


class MCDAScoreResult(BaseModel):
    """Computed MCDA priority score, breakdown, and classification for an issue."""
    issue_id: str
    composite_score: float = Field(..., ge=0.0, le=100.0, description="Final MCDA score between 0 and 100")
    priority_level: PriorityLevel = Field(..., description="LOW, MEDIUM, HIGH, or CRITICAL")
    factor_scores: MCDAFactorScores
    rank: Optional[int] = Field(None, description="Deterministic rank among evaluated issues")


class OptimizationAllocationPlan(BaseModel):
    """Resource allocation recommendation generated by Google OR-Tools."""
    selected_issue_ids: List[str] = Field(default_factory=list, description="Issues recommended for immediate action")
    deferred_issue_ids: List[str] = Field(default_factory=list, description="Issues deferred due to resource constraints")
    total_benefit_score: float = Field(0.0, ge=0.0, description="Sum of MCDA scores for selected issues")
    resource_usage: ResourceUsage


class FactorContribution(BaseModel):
    """MCDA factor contribution breakdown for explainability."""
    factor: str = Field(..., description="MCDA factor name (e.g. severity, urgency)")
    normalized_score: float = Field(..., description="Normalized score on 0-100 scale")
    weight: float = Field(..., description="MCDA factor weight (0.0 - 1.0)")
    weighted_contribution: float = Field(..., description="Weighted points contributed to composite score")


class IssueExplanation(BaseModel):
    """Transparent human-readable decision support breakdown for municipal officers."""
    issue_id: str
    priority_level: PriorityLevel
    composite_score: float
    top_contributing_factors: List[FactorContribution] = Field(
        default_factory=list,
        description="Top contributing MCDA factors ordered by weighted contribution"
    )
    resource_requirements: Dict[str, Optional[float]] = Field(
        default_factory=dict,
        description="Specified resource requirements for resolution"
    )
    recommendation_status: str = Field(
        ...,
        description="RECOMMENDED or DEFERRED"
    )
    reasons: List[str] = Field(
        default_factory=list,
        description="Detailed audit statements explaining score drivers and allocation logic"
    )
    is_recommended_for_allocation: bool = Field(
        ...,
        description="True if selected by optimization, False if deferred"
    )
    allocation_rationale: str = Field(
        ...,
        description="Summary rationale for optimization allocation decision"
    )
    summary: str = Field(
        ...,
        description="High-level human-readable executive summary for municipal officers"
    )
    authority_routing: Optional[AuthorityRoutingResult] = Field(
        None,
        description="Deterministic authority routing and approval hierarchy"
    )


class CIEPipelineResponse(BaseModel):
    """Full end-to-end Civic Intelligence Engine response bundle."""
    validation_reports: List[IssueValidationReport] = Field(
        default_factory=list,
        description="Data validation reports for all evaluated issues"
    )
    valid_issue_count: int = Field(0, description="Total count of issues passing validation")
    flagged_issue_count: int = Field(0, description="Total count of issues flagged with errors/missing data")
    mcda_rankings: List[MCDAScoreResult] = Field(
        default_factory=list,
        description="MCDA scores and deterministic rankings for valid issues"
    )
    allocation_plan: Optional[OptimizationAllocationPlan] = Field(
        None,
        description="OR-Tools resource allocation recommendation plan"
    )
    explanations: List[IssueExplanation] = Field(
        default_factory=list,
        description="Rule-based human-readable explanations per issue"
    )
    status: str = Field(
        "SUCCESS",
        description="Pipeline execution status outcome (e.g. 'SUCCESS', 'NO_FEASIBLE_ISSUES')"
    )

    @property
    def validation_results(self) -> List[IssueValidationReport]:
        """Alias for validation_reports."""
        return self.validation_reports

    @property
    def mcda_results(self) -> List[MCDAScoreResult]:
        """Alias for mcda_rankings."""
        return self.mcda_rankings

    @property
    def optimization_plan(self) -> Optional[OptimizationAllocationPlan]:
        """Alias for allocation_plan."""
        return self.allocation_plan


CIEPipelineResult = CIEPipelineResponse
MCDARanking = MCDAScoreResult
OptimizationResult = OptimizationAllocationPlan
DecisionExplanation = IssueExplanation


class CIEEvaluationRequest(BaseModel):
    """Request payload for CIE end-to-end evaluation."""
    issues: List[CivicIssue] = Field(
        default_factory=list,
        description="List of civic issues to prioritize and optimize"
    )
    resources: MunicipalResources = Field(
        ...,
        description="Available municipal resource constraints"
    )
