import React from 'react';
import { CIEFactors, CivicPriorityLevel } from '../../types';
import { PriorityBadge } from '../common/PriorityBadge';
import { Sparkles, Info } from 'lucide-react';

interface CIEFactorsBreakdownProps {
  score: number;
  level: CivicPriorityLevel;
  factors: CIEFactors;
  populationAffected?: number;
  ageDays?: number;
}

export const CIEFactorsBreakdown: React.FC<CIEFactorsBreakdownProps> = ({
  score,
  level,
  factors,
  populationAffected,
  ageDays,
}) => {
  const factorRows = [
    {
      label: 'Severity',
      value: factors.severity,
      description: 'Physical hazard magnitude & asset deterioration',
    },
    {
      label: 'Urgency',
      value: factors.urgency,
      description: 'Escalation risk if remediation is delayed',
    },
    {
      label: 'Population affected',
      value: factors.population_affected,
      description: populationAffected ? `${populationAffected.toLocaleString('en-IN')} citizens in direct radius` : 'Density impact score',
    },
    {
      label: 'Health/Safety',
      value: factors.health_safety,
      description: 'Biochemical, contamination or traffic accident exposure',
    },
    {
      label: 'Location sensitivity',
      value: factors.location_sensitivity,
      description: 'Proximity to markets, schools, hospitals or transit routes',
    },
    {
      label: 'Complaint age',
      value: factors.complaint_age_days,
      description: ageDays !== undefined ? `Duration since registration (${ageDays} days)` : 'Aging backlog factor',
    },
  ];

  return (
    <div className="bg-white rounded-xl border border-slate-200 p-5 sm:p-6 shadow-xs space-y-5">
      {/* Header with Priority Score */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-200">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-sky-100 text-sky-700">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-900 tracking-tight">
              CIE Priority Analysis
            </h2>
            <p className="text-xs text-slate-500 font-medium">
              Multi-criteria decision support evaluation
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="text-right">
            <div className="text-2xl sm:text-3xl font-black text-slate-900 font-mono tracking-tight leading-none">
              {score}<span className="text-xs text-slate-400 font-normal"> / 100</span>
            </div>
          </div>
          <PriorityBadge level={level} size="lg" />
        </div>
      </div>

      {/* Six Factor Bars */}
      <div className="space-y-4">
        {factorRows.map(row => (
          <div key={row.label} className="space-y-1">
            <div className="flex items-center justify-between text-xs">
              <span className="font-bold text-slate-800">{row.label}</span>
              <span className="font-mono font-bold text-slate-900">{row.value}</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden border border-slate-200">
              <div
                className={`h-full rounded-full transition-all duration-300 ${
                  row.value >= 85
                    ? 'bg-red-600'
                    : row.value >= 70
                    ? 'bg-orange-500'
                    : row.value >= 50
                    ? 'bg-amber-500'
                    : 'bg-emerald-500'
                }`}
                style={{ width: `${row.value}%` }}
              />
            </div>
            <p className="text-[11px] text-slate-400 font-medium">{row.description}</p>
          </div>
        ))}
      </div>

      {/* Explanatory Note */}
      <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-600 flex items-start gap-2 leading-relaxed">
        <Info className="w-4 h-4 text-sky-600 shrink-0 mt-0.5" />
        <span>
          <strong className="text-slate-800 font-semibold">Priority Note: </strong>
          Priority is generated by the Civic Intelligence Engine using backend-provided decision criteria.
        </span>
      </div>
    </div>
  );
};
